# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import replicate_pb2 as replicate__pb2


class ReplicatePostgresToMongodbStub(object):
    """This is the RPC service used to stream data from client to Server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamToServer = channel.unary_unary(
                '/replicate.ReplicatePostgresToMongodb/StreamToServer',
                request_serializer=replicate__pb2.Message.SerializeToString,
                response_deserializer=replicate__pb2.Response.FromString,
                )


class ReplicatePostgresToMongodbServicer(object):
    """This is the RPC service used to stream data from client to Server
    """

    def StreamToServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicatePostgresToMongodbServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamToServer': grpc.unary_unary_rpc_method_handler(
                    servicer.StreamToServer,
                    request_deserializer=replicate__pb2.Message.FromString,
                    response_serializer=replicate__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replicate.ReplicatePostgresToMongodb', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReplicatePostgresToMongodb(object):
    """This is the RPC service used to stream data from client to Server
    """

    @staticmethod
    def StreamToServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/replicate.ReplicatePostgresToMongodb/StreamToServer',
            replicate__pb2.Message.SerializeToString,
            replicate__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
